default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
#  database: admin_rails_development
#  url: <%#= ENV['DATABASE_URL'] %>
  url: <%= ENV['SUPABASE_DATABASE_URL'] || ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: admin_rails_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['SUPABASE_DATABASE_URL'] %>
    # database: admin_rails_production
    # username: admin_rails
    # password: <%= ENV["ADMIN_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: admin_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: admin_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: admin_rails_production_cable
    migrations_paths: db/cable_migrate
